name: preinstalled-software

on: 
 push:
   branches: [main]


jobs:
  check-preinstalled-software:
  runs-on: ubuntu-latest
  steps:
  - name: check versions
    run: echo "${{ docker --version && python --version && git --version && nodejs --version }}"



