name: hello

on:
 push:
   branches: [main]


jobs:
  greet
    runs_on: ubuntu_latest
    steps:
    - name: Checking repo
      run: actions/checkout@v4
    - name: Print message
      run: echo "Hello from GitHub Actions!"  
