name: multijob

on:
 workflow_dispatch:

jobs:
  build:
    steps:
    - name: build
      run: echo "Building the app"
  test:
    needs: build
    steps:
    - name: Testing
      run: echo "Running tests"
  deploy:
    needs: test
    steps:
    - name: deploy
      run: echo "Deploying"
