name: my-self-hosted

on:
 workflow_dispatch:


jobs:
  my-self-job:
    runs-on: aws-self-hosted
    steps:
    - name: Print the hostname of the machine
      run: hostname
    - name: Print the working directory
      run: pwd
    - name: Create a file and verify it exists on your machine after the run
      run: touch hello.txt 




